hmlet_main/api/urls.py
from django.conf.urls import url, include
from . import views


apiurls = [
    url(r'^estate/$', views.EstateListAPIView.as_view(), name='estate'),
    url(r'^estate/(?P<pk>[0-9]+)$', views.EstateAPIView.as_view(), name='estate-detail'),
    url(r'^question/$', views.QuestionListAPIView.as_view(), name='question'),
    url(r'^question/(?P<pk>[0-9]+)$', views.QuestionAPIView.as_view(), name='question-detail'),
]

urlpatterns = [
    url(r'^$', views.api_root, name='api-root'),
    url(r'^', include(apiurls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

hmlet_main/hmlet_main/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^scrape/', include('scrape.urls')),
    url(r'^api/', include('api.urls')),
]

hmlet_main/scrape/urls.py
from django.conf.urls import url
from scrape import views


app_name = 'scrape'
urlpatterns = [
    url(r'^$', views.SearchView.as_view(), name='question'),
    url(r'^results/(?P<pk>[0-9]+)$', views.ResultView.as_view(), name='results'),
]

hmlet_main/scrape/models.py
from django.db import models


class Question(models.Model):
    question = models.CharField(max_length=200)
    ask_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.question
        
        
class Estate(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    link = models.URLField()
    rent = models.FloatField()
    area = models.FloatField()
    raw_text = models.TextField()
    ask_date = models.DateTimeField(auto_now_add=True)
    source = models.CharField(max_length=100)
    location = models.CharField(max_length=200, default = 'default')
    
    
class NestiaEstate(models.Model):
    url = models.URLField(default='default')
    # changed from id in original code
    nestiaId = models.CharField(max_length=200)
    propertyLeaseId = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    street = models.CharField(max_length=200)
    block = models.CharField(max_length=200)
    propertyTypeName = models.CharField(max_length=200)
    propertyTypeCode = models.CharField(max_length=200)
    rentalTypeName = models.CharField(max_length=200)
    rentalTypeCode = models.CharField(max_length=200)
    bedroomNumberName = models.CharField(max_length=200)
    bedroomNumberCode = models.CharField(max_length=200)
    bathroomNumberName = models.CharField(max_length=200)
    bathroomNumberCode = models.CharField(max_length=200)
    roomTypeName = models.CharField(max_length=200)
    roomTypeCode = models.CharField(max_length=200)
    bathroomTypeName = models.CharField(max_length=200)
    bathroomTypeCode = models.CharField(max_length=200)
    price = models.FloatField(default=0)
    ImageURL1 = models.URLField(default='default')
    ImageURL2 = models.URLField(default='default')
    ImageURL3 = models.URLField(default='default')
    ImageURL4 = models.URLField(default='default')
    ImageURL5 = models.URLField(default='default')
    isLike = models.CharField(max_length=200)
    tags = models.CharField(max_length=200)
    subDistrictId = models.CharField(max_length=200)
    latitude = models.CharField(max_length=200)
    longitude = models.CharField(max_length=200)
    projectId = models.CharField(max_length=200)
    isRecommendAgent = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add=True)
    ask_date = models.DateTimeField(auto_now_add=True)

hmlet_main/scrape/forms.py
from django import forms


class QuestionForm(forms.Form):
    question = forms.CharField()
    

hmlet_main/scrape/views.py
import json
from django.shortcuts import get_object_or_404, redirect, render, render_to_response
from .forms import QuestionForm
from django.views import View
from django.views.generic.edit import FormView
from .models import Question, Estate, NestiaEstate
from . import search_func, utils_propertyguru, utils_iproperty, utils_nestia
# from bokeh.plotting import figure, output_file, show 
from bokeh.charts import Histogram, show, output_file
from bokeh.embed import components
import numpy as np


class ResultView(View):
    def get(self, request, pk):
        qns = Question.objects.get(pk=pk)
        estates = Estate.objects.filter(question=qns)
        # draw graph etc
        
        ####################################################################
        
        rents = [i.rent for i in estates]
        area = [i.area for i in estates]
        psf = [x/y for x,y in zip(rents, area)]
        
        hist = Histogram(
            rents,
            ylabel='Count',
            xlabel='Rent($)',
            bins=8,
            title='query: {}'.format(qns.question),
            density=False
            )
        
        hist_psf = Histogram(
            psf,
            ylabel='Count',
            xlabel='Rent per square feet($)',
            bins=8,
            title='query: {}'.format(qns.question),
            density=False
            )
        
        script, div = components(hist)
        script_psf, div_psf = components(hist_psf)
        
        args = {'estates': estates, 'script': script, 'div': div, 'script_psf': script_psf, 'div_psf': div_psf}
        
        return render(request, 'results.html', args)

class SearchView(FormView):
    template_name = 'search.html'
    form_class = QuestionForm
    # success_url = '/scrape/'
        
    def form_valid(self, form, **kwargs):
        q = form.cleaned_data['question']
        if not Question.objects.filter(question=q).exists():
            print('New question')
            qns = Question()
            qns.question = form.cleaned_data['question']
            qns.save()
        else:
            print('Question asked before')
            qns = Question.objects.get(question=q)
        # self.scan_iproperty(qns)
        # self.scan_propertyguru(qns)
        self.scan_nestia(qns)
        # return super(SearchView, self).form_valid(form)
        return redirect('scrape:results', qns.pk)
        
    
    
    def scan_iproperty(self, qns):
        print('Searching iproperty for {}'.format(qns.question))
        
        q, property_list, driver = search_func.set_query_iproperty(qns.question)
        
        for i in property_list:
            # check if exist based on URLField
            link_url = utils_iproperty.get_link(i)
            if not Estate.objects.filter(link=link_url).exists():
                print('--------------------New estate found-----------------------')
                est = Estate()
                est.question = qns
                est.link = link_url
                est.area = utils_iproperty.get_area(i)
                est.rent = utils_iproperty.get_rent(i)
                est.raw_text = i.text
                est.source = 'iproperty'
                est.location = utils_iproperty.get_location(i)
                est.save()
                print(i.text)
            else:
                print("Estate already exists")
        
        driver.quit()
        
    def scan_propertyguru(self, qns):
        print('Searching propertyguru for {}'.format(qns.question))
        
        q, property_list, driver = search_func.set_query_propertyguru(qns.question)
        
        for i in property_list:
            # check if exist based on URLField
            link_url = utils_propertyguru.get_link(i)
            if not Estate.objects.filter(link=link_url).exists():
                print('--------------------New estate found-----------------------')
                est = Estate()
                est.question = qns
                est.link = link_url
                est.area = utils_propertyguru.get_area(i)
                est.rent = utils_propertyguru.get_rent(i)
                est.raw_text = i.text
                est.source = 'propertyguru'
                est.location = utils_propertyguru.get_location(i)
                est.save()
                print(i.text)
            else:
                print("Estate already exists")
        
        driver.quit()
    
    # TODO:  scan nestia here.
    def scan_nestia(self, qns):
        utils_nestia.test(qns)
        utils_nestia.scrape(qns)
        # nest = NestiaEstate()
        # nest.name = qns
        # nest.save()
        
    
    
    

hmlet_main/scrape/templates/results.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Rent Scanner Analysis</title>
   <link rel="stylesheet" href="http://cdn.pydata.org/bokeh/release/bokeh-0.9.0.min.css" type="text/css" />
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

 </head>
 <body>
   <div class="container">
     
     {{ div | safe }}
     {{ div_psf | safe }}
     
     <table style="width:100%">
      <tr>
        <th>Condo Name</th>
        <th>Rent</th>
        <th>Built-up (sf)</th> 
        <th>Source</th>
        <th>Link</th>
      </tr>

     
     {% for estate in estates %}
     <tr>
       <td>{{ estate.location }}</td>
       <td>{{ estate.rent|floatformat:"0" }}</td>
       <td>{{ estate.area|floatformat:"0" }}</td>
       <td>{{ estate.source }}</td>
       <td>
         <a href={{ estate.link }} class="btn btn-default">Link</a>
       </td>
     </tr>
     {% endfor %}
   </table>
     
   </div>

</body>
    <script type="text/javascript" src="http://cdn.pydata.org/bokeh/release/bokeh-0.9.0.min.js"></script>
    {{ script | safe }}
    {{ script_psf | safe }}
    
    <!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
      
    </script>
</html>

hmlet_main/scrape/templates/search.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Rent Scanner</title>

   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

 </head>
 <body>
   <div class="container">
     
     <div class="h-100 row align-items-center" style="padding:200px">
       
       {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
       
       <form action="{% url 'scrape:question' %}" method="post">
         {% csrf_token %}
         <input type="text" name="question" placeholder="Search..."/>
         <input type="submit" value="Scrape" />
       </form>
     </div>


     
   </div>

</body>

    
    <!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
      
    </script>
</html>